# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCUMRSWfW8Mh__bbQXspYW0SoWRu_UDk
"""

# ---------------------------------------------
# CAR PRICE PREDICTION PROJECT (FULL CODING)
# Machine Learning Model: Linear Regression
# ---------------------------------------------

# 1. Install libraries (Colab only)
# !pip install pandas scikit-learn

# 2. Import required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


# ----------------------------------------------------
# 3. Create a sample dataset (replace with your CSV)
# ----------------------------------------------------
data = {
    "year": [2010, 2012, 2013, 2015, 2016, 2017, 2018, 2019, 2020],
    "mileage": [80000, 60000, 65000, 50000, 45000, 40000, 30000, 25000, 15000],
    "engine_cc": [1200, 1400, 1300, 1500, 1600, 1400, 1600, 1500, 1800],
    "price": [250000, 300000, 320000, 450000, 500000, 520000, 650000, 700000, 900000]
}

df = pd.DataFrame(data)
print("Dataset:")
print(df)


# ---------------------------------------------
# 4. Select Features(X) and Target(Y)
# ---------------------------------------------
X = df[["year", "mileage", "engine_cc"]]
y = df["price"]


# ---------------------------------------------
# 5. Split Train/Test Data
# ---------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTraining and Testing Data Prepared.")


# ---------------------------------------------
# 6. Build and Train Model
# ---------------------------------------------
model = LinearRegression()
model.fit(X_train, y_train)

print("\nModel Training Completed.")


# ---------------------------------------------
# 7. Predict Test Data Output
# ---------------------------------------------
y_pred = model.predict(X_test)

print("\nPredicted Prices:")
print(y_pred)


# ---------------------------------------------
# 8. Calculate Model Accuracy
# ---------------------------------------------
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nModel Performance:")
print("Mean Squared Error:", mse)
print("R² Score:", r2)


# ---------------------------------------------
# 9. Predict Car Price for New Input
# ---------------------------------------------
# Example car details:
# Year=2019, Mileage=25000, Engine=1500cc

new_car = [[2019, 25000, 1500]]
predicted_price = model.predict(new_car)

print("\nPredicted Price for New Car:")
print(predicted_price[0])